# Generated by Django 5.1.6 on 2025-02-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=150)),
                ('data', models.DateField(auto_now_add=True)),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
    ]
