# Generated by Django 5.1.6 on 2025-02-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_prioridade_alter_tarefa_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data',
            field=models.DateField(),
        ),
    ]
